### ISSUE TITLE
How does auth work?

### ISSUE THREAD

**Issue by guettli** [hetznercloud/tps-action#10]
From the README:

> It authenticates using the GitHub provided OIDC token for the pipeline run.

Could you please elaborate how auth works?

**Comment by apricote** [comment]
Hey @guettli,

when this action is invoked, we call the [GitHub Actions OIDC](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#updating-your-actions-for-oidc) endpoint to generate an OIDC token signed by GitHub Actions. This token identifies the pipeline (as well as the Repo, Org, Pipeline Creator). 

This token is then being passed to TPS. TPS validates that the OIDC token matches GitHub Actions signature, and then matches the org from the token to a Hetzner account. A new project is then created in the Hetzner Account and the projects token is returned.

Hope this answers your question.
